### ISSUE TITLE
Parser Glob Expressions

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#557]
The parser doesn't seem to be able to handle some expressions in certain cases. For instance, an output section like the one below will work for some steps, but not for others (assuming that `output_file` is truly in the `inputs` section).

```
outputs:
  output:
    type: File
    outputBinding:
      glob: $(inputs.output_file)
```

We noticed this with the Blast workflow, where some steps would work while others would not. This may become more of a problem when we start working with bigger workflows.
